/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Wagdson
 */
public class Conversoes extends javax.swing.JFrame {

    int matrizResultado[][] = new int[2][5];
    int numeroDecimal;

    public Conversoes() {
        initComponents();

    }

    public Conversoes(int[][] matriz) {

        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 5; j++) {
                matrizResultado[i][j] = matriz[i][j];
            }
        }
        initComponents();
        URL caminhoIcone = getClass().getResource("/imagens/ICONE.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        variavelResultado();
        conversao();
        btrBinario.setSelected(true);
        btnLimpar.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        txtConversao.setEditable(false);
        txtResultado.setEditable(false);

    }

    public void variavelResultado() {
        for (int i = 0; i < matrizResultado.length; i++) {
            for (int j = 0; j < matrizResultado[i].length; j++) {
                numeroDecimal += matrizResultado[i][j];

            }

        }
        txtResultado.setText(String.valueOf(numeroDecimal));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        txtConversao = new javax.swing.JTextField();
        lblBase = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btrBinario = new javax.swing.JRadioButton();
        btrOctal = new javax.swing.JRadioButton();
        btrHexadecimal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnConverter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jblfundo = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSÕES");
        setMinimumSize(new java.awt.Dimension(434, 312));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlPrincipal.setBackground(new java.awt.Color(111, 162, 244));
        pnlPrincipal.setOpaque(false);
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(700, 500));
        pnlPrincipal.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setText("DECIMAL:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 17);

        txtResultado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        jPanel4.add(txtResultado);
        txtResultado.setBounds(100, 30, 237, 27);

        txtConversao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtConversao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConversaoActionPerformed(evt);
            }
        });
        jPanel4.add(txtConversao);
        txtConversao.setBounds(100, 80, 239, 20);

        lblBase.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lblBase.setText("BINÁRIO:");
        jPanel4.add(lblBase);
        lblBase.setBounds(20, 80, 70, 17);

        pnlPrincipal.add(jPanel4);
        jPanel4.setBounds(10, 190, 650, 160);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        btg1.add(btrBinario);
        btrBinario.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btrBinario.setText("BINÁRIO");
        btrBinario.setOpaque(false);
        btrBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrBinarioActionPerformed(evt);
            }
        });
        jPanel1.add(btrBinario);
        btrBinario.setBounds(20, 40, 85, 25);

        btg1.add(btrOctal);
        btrOctal.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btrOctal.setText("OCTAL");
        btrOctal.setOpaque(false);
        jPanel1.add(btrOctal);
        btrOctal.setBounds(270, 40, 73, 20);

        btg1.add(btrHexadecimal);
        btrHexadecimal.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btrHexadecimal.setText("HEXADECIMAL");
        btrHexadecimal.setOpaque(false);
        btrHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrHexadecimalActionPerformed(evt);
            }
        });
        jPanel1.add(btrHexadecimal);
        btrHexadecimal.setBounds(500, 40, 127, 25);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("OPÇÕES DE BASES NUMÉRICAS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 10, 280, 21);

        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechar);
        btnFechar.setBounds(380, 80, 150, 25);

        btnLimpar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(210, 80, 150, 25);

        btnConverter.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnConverter.setText("CONVERTER");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });
        jPanel1.add(btnConverter);
        btnConverter.setBounds(40, 80, 150, 25);

        pnlPrincipal.add(jPanel1);
        jPanel1.setBounds(10, 10, 650, 120);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULTADO");
        pnlPrincipal.add(jLabel2);
        jLabel2.setBounds(20, 170, 85, 17);

        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(10, 20, 670, 360);

        jblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cropped-800-600-913942.jpg"))); // NOI18N
        jblfundo.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jblfundo);
        jblfundo.setBounds(-10, 0, 730, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtConversaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConversaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConversaoActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        conversao();
        btnLimpar.setEnabled(true);
        btnConverter.setEnabled(false);
        ativarOpcoes();
      

    }//GEN-LAST:event_btnConverterActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtConversao.setText(" ");
        btnConverter.setEnabled(true);
        btnLimpar.setEnabled(false);
        desativarOpcoes();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btrBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrBinarioActionPerformed

    }//GEN-LAST:event_btrBinarioActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btrHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrHexadecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btrHexadecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JButton btnConverter;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton btrBinario;
    private javax.swing.JRadioButton btrHexadecimal;
    private javax.swing.JRadioButton btrOctal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jblfundo;
    private javax.swing.JLabel lblBase;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtConversao;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
public void conversao() {
        /*
    Coverter para Binário
         */
        boolean numeroVezes = true;
        int quonciente;
        int resto;
        int contador;
        int numeroBinario = numeroDecimal;
        int numeroOctal = numeroDecimal;
        int numeroHexadecimal = numeroDecimal;
        String valorBinario = "";

        String restoLetra = "";
        if (btrBinario.isSelected()) {
            String B1 = "";
            while (numeroVezes) {
                resto = numeroBinario % 2;
                quonciente = numeroBinario / 2;
                numeroBinario = quonciente;
                valorBinario += String.valueOf(resto);
                if (numeroBinario <= 1) {
                    numeroVezes = false;
                    if (numeroBinario == 1) {
                        valorBinario += String.valueOf(numeroBinario);
                    }
                }
            }

            contador = valorBinario.length();

            for (int i = valorBinario.length() - 1; i >= 0; i--) {

                B1 += valorBinario.charAt(i);
            }
            txtConversao.setText(B1);
        }
        /*
        Converter para Octal 
         */
        if (btrOctal.isSelected()) {
            lblBase.setText("Octal:");
            String O1 = "";
            numeroVezes = true;
            String valorOctal = "";
            restoLetra = "";
            while (numeroVezes) {
                resto = numeroOctal % 8;
                quonciente = numeroOctal / 8;
                numeroOctal = quonciente;

                valorOctal += String.valueOf(resto);

                if (numeroOctal <= 1) {
                    numeroVezes = false;
                    if (numeroOctal == 1) {
                        valorOctal += String.valueOf(numeroOctal);
                    }
                }
            }
            contador = valorOctal.length();

            for (int i = valorOctal.length() - 1; i >= 0; i--) {

                O1 += valorOctal.charAt(i);
            }
            txtConversao.setText(O1);
        }
        /*
Converter para Hexadecimal
         */
        if (btrHexadecimal.isSelected()) {
            numeroVezes = true;
            String valorHexadecimal = "";
            String C1 = "";

            while (numeroVezes) {
                resto = numeroHexadecimal % 16;
                quonciente = numeroHexadecimal / 16;
                numeroHexadecimal = quonciente;
                if (resto > 9 && resto < 16) {
                    if (resto == 10) {
                        restoLetra = "A";
                    }
                    if (resto == 11) {
                        restoLetra = "B";
                    }
                    if (resto == 12) {
                        restoLetra = "C";
                    }
                    if (resto == 13) {
                        restoLetra = "D";
                    }
                    if (resto == 14) {
                        restoLetra = "E";
                    }
                    if (resto == 15) {
                        restoLetra = "F";
                    }
                    valorHexadecimal += restoLetra;
                } else {
                    valorHexadecimal += String.valueOf(resto);
                }

                if (numeroHexadecimal <= 1) {
                    numeroVezes = false;
                    if (numeroHexadecimal == 1) {
                        valorHexadecimal += String.valueOf(numeroHexadecimal);
                    }
                }

            }

            contador = valorHexadecimal.length();

            for (int i = valorHexadecimal.length() - 1; i >= 0; i--) {

                C1 += valorHexadecimal.charAt(i);
            }
            txtConversao.setText(C1);

        }

    }

    public void desativarOpcoes() {
       
    }

    public void ativarOpcoes() {
      
    }
}
